Repository GetStream/stream-chat-android, pull requests merged in 2022-08, with the labels that each got.

#3969 [ISSUE-3699] Delete message listener separation
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteMessageListenerComposite.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteMessageListenerDatabase.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteMessageListenerDatabaseTest.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteMessageListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteMessageListenerStateTest.kt
Labels: core, merge-before-release

#3637 [3563] Add a typing update pruning mechanism
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/TypingEventPruner.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/internal/GlobalMutableState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/internal/TypingEventPrunerTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImplTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/reactions/DeleteReactionsTests.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/reactions/SendReactionsTests.kt
Labels: merge-before-release

#3962 Making initialization state clearer
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/InitializationState.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientMutableState.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientState.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/internal/ClientStateImpl.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/Mother.kt
Labels: core, merge-before-release

#3985 [3984] mark channel as read when opening from push notification
  CHANGELOG.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ChannelApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/utils/internal/ChannelMarkReadHelper.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/channel/ChannelMarkReadHelperTests.kt
Labels: core

#3990 [3989] Update screenshots for snapshot tests
  stream-chat-android-ui-uitests/screenshots/debug/io.getstream.chat.android.uitests.snapshot.compose.messages.SelectedMessageMenuTest_selectedMessageMenuForTheirMessage.png
  stream-chat-android-ui-uitests/screenshots/debug/io.getstream.chat.android.uitests.snapshot.compose.messages.SelectedMessageMenuTest_selectedMessageMenuForTheirMessage_dark.png
Labels: compose, ui-components

#3992 Improve ChatEventHandler performance
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-compose/detekt-baseline.xml
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModel.kt
  stream-chat-android-state/api/stream-chat-android-state.api
  stream-chat-android-state/detekt-baseline.xml
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/DefaultChatEventHandler.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/factory/ChatEventHandlerFactory.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/internal/ChatClientStateCalls.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/querychannels/QueryChannelsState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/querychannels/internal/QueryChannelsMutableState.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandlerTest.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/CustomEventHandler.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
Labels: compose, ui-components, core

#3999 Update channels list after receiving new message event
  CHANGELOG.md
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/DefaultChatEventHandler.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandlerTest.kt
Labels: core

#3993 [ISSUE-3708] Send reaction listener impl separation
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/SendReactionListenerComposite.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/SendReactionListenerDatabase.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/SendReactionListenerDatabaseTest.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/SendReactionListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/reactions/SendReactionListenerStateTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/reactions/SendReactionsTests.kt
Labels: core

#4002 [3961] Fix crash when attaching photo
  CHANGELOG.md
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/StorageHelper.kt
Labels: compose, ui-components

#3959 [3956] Make ThreadState independent from ChannelState
  .idea/inspectionProfiles/ktlint.xml
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/MessageRepository.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/noop/NoOpMessageRepository.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/DatabaseMessageRepository.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageDao.kt
  stream-chat-android-state/api/stream-chat-android-state.api
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerSequential.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteMessageListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteReactionListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/EditMessageListenerImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/SendGiphyListenerImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/SendMessageListenerImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/SendReactionListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ShuffleGiphyListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/thread/internal/ThreadLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/thread/internal/ThreadStateLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/thread/internal/ThreadStateLogicImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/StateRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/channel/thread/ThreadState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/channel/thread/internal/ThreadMutableState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/channel/thread/internal/ThreadMutableStateImpl.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/channel/controller/attachment/UploadAttachmentsIntegrationTests.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImplTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/DeleteMessageListenerStateTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/ShuffleGiphyListenerStateTest.kt
Labels: core

#4005 [ISSUE-3697] Mark read listeners rename
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ChannelMarkReadListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/MarkAllReadListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/utils/internal/ChannelMarkReadHelper.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/channel/ChannelMarkReadHelperTests.kt
Labels: core

#3994 [39] Attachments picker customization options
  CHANGELOG.md
  docusaurus/docs/Android/04-compose/03-general-customization/01-chat-theme.mdx
  docusaurus/docs/Android/04-compose/05-message-components/05-attachments-picker.mdx
  docusaurus/docs/Android/assets/compose_custom_attachments_picker_tabs.png
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/detekt-baseline.xml
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/state/messages/attachments/AttachmentsPickerMode.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/AttachmentsPicker.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerFilesTabFactory.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerImagesTabFactory.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerMediaCaptureTabFactory.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerTabFactories.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerTabFactory.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/MissingPermissionContent.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/StorageHelperWrapper.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/AttachmentsPickerViewModel.kt
  stream-chat-android-compose/src/main/res/drawable/stream_compose_ic_file_picker.xml
  stream-chat-android-compose/src/main/res/drawable/stream_compose_ic_image_picker.xml
  stream-chat-android-compose/src/main/res/drawable/stream_compose_ic_media_picker.xml
Labels: compose

#3976 [ISSUE-3899] update dependencies
  CHANGELOG.md
  buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
  config/detekt/detekt.yml
  libraries/logging/stream-logger-android-init/build.gradle
  libraries/logging/stream-logger-android/build.gradle
  libraries/logging/stream-logger-file/build.gradle
  libraries/logging/stream-logger-file/src/main/java/io/getstream/logging/file/FileStreamLogger.kt
  libraries/logging/stream-logger/build.gradle
  stream-chat-android-client-test/build.gradle
  stream-chat-android-client/build.gradle
  stream-chat-android-client/detekt-baseline.xml
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/receivers/NotificationMessageReceiver.kt
  stream-chat-android-compose-sample/build.gradle
  stream-chat-android-compose-sample/detekt-baseline.xml
  stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt
  stream-chat-android-compose/build.gradle
  stream-chat-android-compose/detekt-baseline.xml
  stream-chat-android-core/build.gradle
  stream-chat-android-docs/build.gradle
  stream-chat-android-markdown-transformer/build.gradle
  stream-chat-android-offline/build.gradle
  stream-chat-android-pushprovider-firebase/build.gradle
  stream-chat-android-pushprovider-huawei/build.gradle
  stream-chat-android-pushprovider-xiaomi/build.gradle
  stream-chat-android-state/build.gradle
  stream-chat-android-state/detekt-baseline.xml
  stream-chat-android-test/build.gradle
  stream-chat-android-ui-common/build.gradle
  stream-chat-android-ui-common/detekt-baseline.xml
  stream-chat-android-ui-components-sample/build.gradle
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
  stream-chat-android-ui-components/build.gradle
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/suggestion/list/SuggestionListControllerListener.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/transformer/AutoLinkableTextTransformer.kt
  stream-chat-android-ui-uitests/build.gradle
  stream-chat-android-ui-uitests/detekt-baseline.xml
  stream-chat-android-ui-utils/build.gradle
Labels: core

#4011 [3176] Apply fixed image and link dimensions in order to avoid items jumping upon loading
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/AttachmentMapping.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/AttachmentDto.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Attachment.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/AttachmentDtoTestData.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/attachment/internal/AttachmentEntity.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/attachment/internal/AttachmentMapper.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/CoilStreamImageLoader.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/ImageAttachmentsGroupView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/LinkAttachmentView.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_link_attachments_view.xml
Labels: ui-components

#4025 Update deprecations
  DEPRECATIONS.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QuerySort.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/ChatLogger.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/ChatLoggerImpl.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/ChatSilentLogger.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/TaggedLogger.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/TaggedLoggerImpl.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/Mother.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/InputField.kt
  stream-chat-android-state/api/stream-chat-android-state.api
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/LegacyDateFormatter.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/typing/DefaultTypingUpdatesBuffer.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/viewmodel/MessageInputViewModelBinding.kt
  stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/ui/BaseUiTest.kt
  stream-chat-android-ui-uitests/src/main/java/io/getstream/chat/android/uitests/app/compose/ComposeChannelsActivity.kt
  stream-chat-android-ui-uitests/src/main/java/io/getstream/chat/android/uitests/app/uicomponents/UiComponentsChannelsActivity.kt
Labels: merge-before-release

#4031 [3814] cancel children jobs when ChatClient gets disconnected
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/coroutine/CoroutineContext.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/BlockedTask.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/call/CoroutineCallTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt
  stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/CoroutineCall.kt
  stream-chat-android-test/src/main/java/io/getstream/chat/android/test/MockRetrofitCall.kt
Labels: core, merge-before-release

#4013 [3176] Apply fixed image dimensions
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/ImageAttachmentContent.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/ImageAttachmentFactory.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamDimens.kt
Labels: compose, merge-before-release

#4030 [ISSUE-4029] Diff with only non null unread count.
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Channel.kt
Labels: ui-components, merge-before-release

#4035 [4034] Fix own reactions
  CHANGELOG.md
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
Labels: compose, ui-components, core, merge-before-release

#4028 [ISSUE-3710] Thread query listener impl separation
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerFull.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/thread/internal/ThreadLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
Labels: core, merge-before-release

#4038 [4037] fix query channels request not being fire on app launch
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
Labels: core

#4040 [3879] move retryFailedEntities invocation before the syncing
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
Labels: core

#4050 [4044] Fix avatar in navigation drawer
  CHANGELOG.md
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragmentViewModel.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeViewModel.kt
Labels: ui-components

#4055 [ISSUE-3706] SendGiphyListener as state
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/SendGiphyListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/thread/internal/ThreadLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
Labels: core

#4043 [3970] Fix watcher count
  CHANGELOG.md
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
Labels: compose

#4057 [4054] Command button visibility
  CHANGELOG.md
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerState.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerLeadingContent.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
Labels: compose, ui-components

#4041 [4003] Fix commands button
  CHANGELOG.md
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerView.kt
Labels: ui-components

#4061 [3963] Side effects for DistinctCalls run multiple times
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QueryChannelRequest.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/identifier/Identifiers.kt
  stream-chat-android-core/api/stream-chat-android-core.api
  stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/Call.kt
  stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/DistinctCall.kt
  stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/SharedCalls.kt
  stream-chat-android-ui-components-sample/detekt-baseline.xml
Labels: core

#4056 [ISSUE-3702] Separate HideChannelListenerImpl
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/HideChannelListenerComposite.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/HideChannelListenerDatabase.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/HideChannelListenerDatabaseTest.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/HideChannelListenerState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/channel/controller/WhenHandleEvent.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/listener/internal/HideChannelListenerStateTest.kt
Labels: core

#4024 [43] Migrate guides to the main repo
  .github/CODEOWNERS
  CHANGELOG.md
  settings.gradle
  stream-chat-android-ui-guides/.gitignore
  stream-chat-android-ui-guides/api/stream-chat-android-ui-guides.api
  stream-chat-android-ui-guides/build.gradle
  stream-chat-android-ui-guides/detekt-baseline.xml
  stream-chat-android-ui-guides/proguard-rules.pro
  stream-chat-android-ui-guides/src/main/AndroidManifest.xml
  stream-chat-android-ui-guides/src/main/ic_launcher-playstore.png
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/ChatUI.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/GuidesApp.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/CatalogActivity.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/compose/customattachments/ChannelsActivity.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/compose/customattachments/MessagesActivity.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/compose/customattachments/factory/DateAttachmentFactory.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/compose/customattachments/factory/QuotedDateAttachmentFactory.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/composer/ChannelsActivity.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/composer/MessagesActivity.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/composer/factory/DateAttachmentFactory.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/composer/factory/DateAttachmentPreviewFactory.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/composer/factory/QuotedDateAttachmentFactory.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/input/ChannelsActivity.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/input/MessagesActivity.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/input/factory/DateAttachmentFactory.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/input/factory/DateAttachmentPreviewFactory.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/catalog/uicomponents/customattachments/input/factory/QuotedDateAttachmentFactory.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/login/LoginActivity.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/login/LoginUser.kt
  stream-chat-android-ui-guides/src/main/java/io/getstream/chat/android/guides/login/LoginUsers.kt
  stream-chat-android-ui-guides/src/main/res/drawable/ic_arrow.xml
  stream-chat-android-ui-guides/src/main/res/drawable/ic_calendar.xml
  stream-chat-android-ui-guides/src/main/res/drawable/ic_close.xml
  stream-chat-android-ui-guides/src/main/res/drawable/ic_logout.xml
  stream-chat-android-ui-guides/src/main/res/drawable/ic_stream.xml
  stream-chat-android-ui-guides/src/main/res/layout/activity_messages.xml
  stream-chat-android-ui-guides/src/main/res/layout/custom_message_composer_leading_content.xml
  stream-chat-android-ui-guides/src/main/res/layout/item_date_attachment.xml
  stream-chat-android-ui-guides/src/main/res/layout/item_date_attachment_preview.xml
  stream-chat-android-ui-guides/src/main/res/layout/view_quoted_date_attachment.xml
  stream-chat-android-ui-guides/src/main/res/mipmap-hdpi/ic_launcher.png
  stream-chat-android-ui-guides/src/main/res/mipmap-hdpi/ic_launcher_round.png
  stream-chat-android-ui-guides/src/main/res/mipmap-mdpi/ic_launcher.png
  stream-chat-android-ui-guides/src/main/res/mipmap-mdpi/ic_launcher_round.png
  stream-chat-android-ui-guides/src/main/res/mipmap-xhdpi/ic_launcher.png
  stream-chat-android-ui-guides/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  stream-chat-android-ui-guides/src/main/res/mipmap-xxhdpi/ic_launcher.png
  stream-chat-android-ui-guides/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  stream-chat-android-ui-guides/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  stream-chat-android-ui-guides/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  stream-chat-android-ui-guides/src/main/res/values/strings.xml
  stream-chat-android-ui-guides/src/main/res/values/themes.xml
  stream-chat-android-ui-guides/src/main/res/xml/network_security_config.xml
Labels: compose, ui-components

#4067 [4066] Fix image attachments without dimensions not loading
  CHANGELOG.md
  buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/ImageAttachmentsGroupView.kt
Labels: ui-components

#4072 [4070] Decrement online count
  CHANGELOG.md
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
Labels: core

#4077 [4068] Create PR on Snapshot-Record action
  .github/workflows/snapshot-record.yaml
  scripts/uitests/start_emulator.sh
Labels: compose, ui-components

#4074 [4073] Use quote-message capability to cotrol reply option
  CHANGELOG.md
  stream-chat-android-compose/detekt-baseline.xml
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptions.kt
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/MessageOptionItemsFactory.kt
Labels: compose, ui-components

#4083 [4082] Make EventHandlerSequential as a default one
  CHANGELOG.md
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/configuration/StatePluginConfig.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
Labels: core

#4026 [ISSUE-3972] Switch User 2
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocket.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/common/Extensions.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeFragment.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/home/HomeViewModel.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginFragment.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/user_login/UserLoginViewModel.kt
  stream-chat-android-ui-components-sample/src/main/res/layout/fragment_home.xml
  stream-chat-android-ui-components-sample/src/main/res/values/strings.xml
Labels: merge-before-release

#4095 Update DEPRECATIONS.md
  DEPRECATIONS.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MemberMapping.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamDimens.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/member/internal/MemberMapper.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/ChatEventHandler.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/NonMemberChatEventHandler.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/querychannels/QueryChannelsState.kt
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/LegacyDateFormatter.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/roundedImageView/PorterImageView.java
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/roundedImageView/PorterShapeImageView.java
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/typing/DefaultTypingUpdatesBuffer.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
Labels: merge-before-release

#4107 [4097] Fix Integration buttons Attribute Compliance
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerLeadingContent.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
Labels: merge-before-release

#4105 [4101] Fix list scroll on filter change
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt
Labels: ui-components, merge-before-release
