Repository GetStream/stream-chat-android, pull requests merged in 2022-09, with the labels that each got.

#4120 [3530] Improve slow mode
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/ChannelCapabilities.kt
  stream-chat-android-compose/detekt-baseline.xml
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerTrailingContent.kt
Labels: compose, ui-components

#4127 [4092] Expose MessageOptionsDialogFragment
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/internal/FullScreenDialogFragment.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/MessageOptionsDialogFragment.kt
Labels: ui-components

#4110 Add a `StreamHandsOff` comment to prevent reflection errors
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/notifications/StreamCoilUserIconBuilder.kt
Labels: core, merge-before-release

#4027 [4023] Improve Giphy rendering
  CHANGELOG.md
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/StreamAttachmentFactories.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/GiphyAttachmentContent.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/factory/GiphyAttachmentFactory.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/GiphyMessageContent.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamDimens.kt
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/utils/GiphyInfoType.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/utils/GiphySizingMode.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
Labels: compose, merge-before-release

#4139 Update DEPRECATIONS.md
  DEPRECATIONS.md
  docusaurus/docs/Android/03-ui/04-message-components/02-message-list.mdx
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/ChatLogger.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/ChatLoggerImpl.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/ChatSilentLogger.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/TaggedLogger.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/TaggedLoggerImpl.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientState.kt
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamDimens.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageList.kt
  stream-chat-android-state/api/stream-chat-android-state.api
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/ChatEventHandler.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/DefaultChatEventHandler.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/chat/NonMemberChatEventHandler.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/utils/SelfUserUtils.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/GlobalState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/internal/GlobalMutableState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/internal/MutableGlobalState.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/state/MessageAction.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/MessageOptionItemsFactory.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/viewmodel/MessageListViewModelBinding.kt
  stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/uicomponents/channels/ChannelListViewTest.kt
Labels: merge-before-release

#4134 [4023] Improve Giphy resizing
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/GiphyMediaAttachmentViewStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/GiphyMediaAttachmentView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/GiphyAttachmentViewHolder.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_giphy_media_attachment_view.xml
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_giphy_attachment.xml
  stream-chat-android-ui-components/src/main/res/values/attrs_giphy_media_attachment_view.xml
  stream-chat-android-ui-components/src/main/res/values/styles.xml
Labels: ui-components, merge-before-release

#4145 [4048] SyncManager doesn't use lastSyncedAt from DB as a fallback value
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
Labels: core, merge-before-release

#4123 [3793] Refactor QueryChannelsPostponeHelper to make it event driven
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/SocketState.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/SocketStateService.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/helpers/CallPostponeHelper.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/experimental/ChatSocket.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/experimental/ChatSocketStateService.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/helpers/CallPostponeHelperTests.kt
Labels: core, merge-before-release

#4138 Review connectionId usages
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitCdnApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/MoshiChatApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ChannelApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/DeviceApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/GeneralApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/MessageApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/endpoint/ModerationApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/FileUploader.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/uploader/StreamFileUploaderTest.kt
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/helpers/MyFileUploader.java
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/helpers/MyFileUploader.kt
Labels: core

#4153 GH-Action to check DB Entities
  .github/workflows/check-entities.yml
Labels: merge-before-release

#4159 Improve sample apps description
  docs/compose-sample-attachments-gallery.png
  docs/compose-sample-attachments-picker.png
  docs/compose-sample-channel-actions.png
  docs/compose-sample-channels-dark.png
  docs/compose-sample-channels-light.png
  docs/compose-sample-channels.png
  docs/compose-sample-message-options.png
  docs/compose-sample-messages-dark.png
  docs/compose-sample-messages-light.png
  docs/compose-sample-messages.png
  docs/compose-sample-reaction-options.png
  docs/compose-sample-user-login.png
  docs/compose-sample-video.gif
  docs/sample-attachments-picker.png
  docs/sample-channel-actions.png
  docs/sample-channel-details.png
  docs/sample-channels-dark.png
  docs/sample-channels-light.png
  docs/sample-channels.png
  docs/sample-login-dark.png
  docs/sample-login-light.png
  docs/sample-message-options.png
  docs/sample-messages-dark.png
  docs/sample-messages-light.png
  docs/sample-messages.png
  docs/sample-reaction-options.png
  docs/sample-user-login.png
  docs/sample-video.gif
  stream-chat-android-compose-sample/README.md
  stream-chat-android-compose/README.md
  stream-chat-android-ui-components-sample/README.md
  stream-chat-android-ui-components/README.md
Labels: compose, ui-components, merge-before-release

#4175 Exposed own/other message text color customization options
  CHANGELOG.md
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/QuotedMessageText.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/TextUtils.kt
Labels: compose

#4176 Upgrade dependencies
  buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
Labels: merge-before-release

#4183 Task/improve compose screen components
  CHANGELOG.md
  docusaurus/docs/Android/04-compose/04-channel-components/01-channels-screen.mdx
  docusaurus/docs/Android/04-compose/05-message-components/01-messages-screen.mdx
  stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/ChannelsActivity.kt
  stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/MessagesActivity.kt
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/ChannelsScreen.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/MessagesScreen.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channels/ChannelViewModelFactory.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/channels/ChannelsScreen.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/general/ChatTheme.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/guides/ProvidingCustomReactions.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/messages/MessagesScreen.kt
  stream-chat-android-ui-uitests/src/main/java/io/getstream/chat/android/uitests/app/compose/ComposeMessagesActivity.kt
Labels: compose, v6-candidate

#4207 [4193] Remove old event handler
  CHANGELOG.md
  docusaurus/docs/Android/01-basics/04-getting-started.mdx
  docusaurus/docs/Android/02-client/06-guides/06-offline-support.mdx
  docusaurus/docs/Android/02-client/06-guides/07-chatdomain-migration.mdx
  stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/ChatDomainMigration.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/GettingStarted.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/Offline.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/configuration/Config.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-state/api/stream-chat-android-state.api
  stream-chat-android-state/detekt-baseline.xml
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/configuration/StatePluginConfig.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/event/TotalUnreadCountTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/event/model/EventHandlerType.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
Labels: core

#4222 Fix parsing of giphy size
  CHANGELOG.md
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/utils/GiphyInfoType.kt
Labels: ui-components
