Repository GetStream/stream-chat-android, pull requests merged in 2022-07, with the labels that each got.

#3778 Add ordered substitution arguments in `ja` and `ko` translated strings files (#3767)
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/res/values-ja/strings_attachment_gallery.xml
  stream-chat-android-ui-components/src/main/res/values-ja/strings_message_list.xml
  stream-chat-android-ui-components/src/main/res/values-ja/strings_message_list_header.xml
  stream-chat-android-ui-components/src/main/res/values-ko/strings_attachment_gallery.xml
  stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list.xml
  stream-chat-android-ui-components/src/main/res/values-ko/strings_message_list_header.xml
Labels: merge-before-release

#3810 [3714] Add lifecycle publisher tests
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/experimental/socket/lifecycle/ConnectionLifecyclePublisherTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/experimental/socket/lifecycle/FakeLifecyclePublisher.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/experimental/socket/lifecycle/LifecyclePublisherTest.kt
Labels: core

#3782 [3780] cover an edge case inside default typing updates buffer
  CHANGELOG.md
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/typing/DefaultTypingUpdatesBuffer.kt
Labels: merge-before-release

#3806 Add GlobalState::typingChannels that exposes typing users in all active channels
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/channel/internal/ChannelMutableState.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/global/GlobalState.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/global/internal/GlobalMutableState.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/global/internal/MutableGlobalState.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
Labels: core, merge-before-release

#3816 [3815] Crash at ExtraDataConverter.stringToMap
  CHANGELOG.md
  stream-chat-android-offline/src/main/java/com/squareup/moshi/MultiMapJsonAdapter.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/converter/internal/ConverterMoshiInstance.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/database/converter/ExtraDataConverterTest.kt
  stream-chat-android-test/src/main/java/io/getstream/chat/android/test/MultiMap.kt
Labels: core, merge-before-release

#3690 Channel logic state separation
  stream-chat-android-compose-sample/detekt-baseline.xml
  stream-chat-android-offline/detekt-baseline.xml
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/attachments/internal/AttachmentUrlValidator.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/attachments/internal/UploadAttachmentsAndroidWorker.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/attachments/internal/UploadAttachmentsWorker.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/model/channel/ChannelData.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/model/message/attachments/UploadAttachmentsNetworkType.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/SearchLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/ChannelStateLogicProvider.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/StateRegistry.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/channel/MessagesState.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/channel/internal/ChannelMutableState.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/state/channel/internal/ChannelMutableStateImpl.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/ChannelMarkReadHelperTests.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/WhenHandleEvent.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/attachment/AttachmentUploaderTests.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/attachment/UploadAttachmentsIntegrationTests.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/attachment/WhenUploadAttachmentsTests.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/events/TypingEventsTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImplTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/reactions/DeleteReactionsTests.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/reactions/SendReactionsTests.kt
  stream-chat-android-ui-components/detekt-baseline.xml
Labels: merge-before-release

#3830 [3829] Fix sectioned avatars
  stream-chat-android-offline/src/main/java/com/squareup/moshi/MultiMapJsonAdapter.kt
Labels: core

#3835 [3834] notification is not visible
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Labels: core

#3839 [3837] Use correct viewholder for uploading state
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemViewTypeMapper.kt
Labels: ui-components

#3858 Show snackbar on file to large error
  CHANGELOG.md
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
Labels: compose

#3851 [3734] Remove `Member.isOwner` extension
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-client-test/api/stream-chat-android-client-test.api
  stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/Mother.kt
  stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/utils/TestDataHelper.kt
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MemberMapping.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/MemberDtos.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Member.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/ChannelDtoTestData.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/member/internal/MemberMapper.kt
  stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/Mother.kt
  stream-chat-android-ui-components-sample/detekt-baseline.xml
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/common/Extensions.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoFragment.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoItem.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewHolders.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewModel.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoFragment.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/group/GroupChatInfoViewModel.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/Mother.kt
  stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/util/TestData.kt
Labels: ui-components

#3861 Fixing search messages
  CHANGELOG.md
  stream-chat-android-state/.env
  stream-chat-android-state/build.gradle
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/event/EventHandlerImplTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/event/TotalUnreadCountTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImplTest.kt
  stream-chat-android-state/src/test/resources/channels.json
Labels: core

#3860 [3216] Write UI comp ViewModel tests
  stream-chat-android-ui-components/build.gradle
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/MockChatClientBuilder.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/ChannelListViewModelTest.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/MessageInputViewModelTest.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/MessageListViewModelTest.kt
Labels: ui-components

#3867 [3868] Socket does not reconnect on logout/login flow
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/plugin/factory/StreamOfflinePluginFactory.kt
Labels: core

#3857 [3779] Clean up static references in dialogs
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/actions/internal/ChannelActionsDialogFragment.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/actions/internal/ChannelActionsViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/options/internal/AttachmentGalleryOptionsDialogFragment.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/dialog/ModeratedMessageDialogFragment.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/attachment/AttachmentSelectionDialogFragment.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt
Labels: ui-components

#3871 Add state module to CODEOWNERS
  .github/CODEOWNERS
Labels: core

#3869 [3601] Provide StreamLog & ChatLoggerHandler connection layer
  CHANGELOG.md
  libraries/logging/stream-logger/src/main/java/io/getstream/logging/StreamLog.kt
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/ChatLoggerHandler.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/ChatLoggerImpl.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/StreamLogLevelValidator.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/logger/StreamLoggerHandler.kt
Labels: core

#3844 [3777] Document MessageComposerView
  CHANGELOG.md
  docusaurus/docs/Android/03-ui/04-message-components/05-message-composer.mdx
  docusaurus/docs/Android/assets/message_composer.png
  docusaurus/docs/Android/assets/message_composer_custom_attribute.png
  docusaurus/docs/Android/assets/message_composer_custom_slot_1.png
  docusaurus/docs/Android/assets/message_composer_custom_slot_2.png
  docusaurus/docs/Android/assets/message_composer_whole_screen.png
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageComposer.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageInput.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageListHeader.kt
  stream-chat-android-docs/src/main/res/layout/custom_message_composer_leading_content.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerView.kt
Labels: ui-components, merge-before-release

#3882 [3881] Expose message position handler
  CHANGELOG.md
  stream-chat-android-client/detekt-baseline.xml
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/detekt-baseline.xml
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
  stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveDataTest.kt
Labels: ui-components, merge-before-release

#3883 Update deprecations
  DEPRECATIONS.md
  stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/utils/TestDataHelper.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QuerySort.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/models/QuerySortTest.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/InputField.kt
  stream-chat-android-compose/src/test/kotlin/io/getstream/chat/android/compose/viewmodel/channels/ChannelListViewModelTest.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/Messages.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/Mother.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/BaseDomainTest2.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/QueryChannelsImplRepositoryTest.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/GlobalState.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/internal/extensions/ChannelExtensionsTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/querychannels/QueryChannelsSortTest.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/common/Extensions.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/viewmodel/MessageInputViewModelBinding.kt
Labels: merge-before-release

#3877 [3845] Update custom attachments guide
  CHANGELOG.md
  docusaurus/docs/Android/03-ui/06-guides/08-adding-custom-attachments-message-input.mdx
  docusaurus/docs/Android/03-ui/06-guides/09-adding-custom-attachments-message-composer.mdx
  docusaurus/docs/Android/assets/quoted_attachment_final_v2.png
  docusaurus/docs/Android/assets/rendering_custom_attachments_v2.png
  docusaurus/docs/Android/assets/sending_custom_attachments_v2_1.png
  docusaurus/docs/Android/assets/sending_custom_attachments_v2_2.png
  docusaurus/docs/Android/assets/sending_custom_attachments_v2_3.png
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/guides/AddingCustomAttachmentsMessageComposer.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/guides/AddingCustomAttachmentsMessageInput.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageComposer.kt
  stream-chat-android-docs/src/main/res/layout/custom_message_composer_leading_content.xml
  stream-chat-android-docs/src/main/res/layout/message_composer_leading_content.xml
Labels: ui-components, merge-before-release

#3887 Fix scroll on new message
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/Messages.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/internal/MessageListScrollHelper.kt
Labels: compose, ui-components, merge-before-release

#3888 Not clearing instances of registries
  CHANGELOG.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/SocketStateService.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/clientstate/UserStateService.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/InitializationCoordinator.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/StateRegistry.kt
Labels: merge-before-release

#3890 Update snippets
  docusaurus/docs/Android/02-client/06-guides/01-push-notifications/01-overview.mdx
  docusaurus/docs/Android/02-client/06-guides/01-push-notifications/03-huawei.mdx
  docusaurus/docs/Android/02-client/06-guides/01-push-notifications/04-xiaomi.mdx
  docusaurus/docs/Android/02-client/06-guides/07-chatdomain-migration.mdx
  libraries/external/MiPush_SDK_Client_5_0_6-G_3rd.aar
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/querysort/QuerySortByField.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Member.kt
  stream-chat-android-docs/build.gradle
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/AndroidIntroduction.java
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Channels.java
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/ClientAndUsers.java
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Messages.java
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/Moderation.java
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/cms/UnreadCounts.java
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/AndroidIntroduction.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/Channels.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/ClientAndUsers.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/Messages.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/Moderation.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/UnreadCounts.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/ChatDomainMigration.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/CoreConcepts.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/GettingStarted.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/Offline.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/Push.kt
  stream-chat-android-pushprovider-xiaomi/build.gradle
  stream-chat-android-ui-components-sample/build.gradle
  stream-chat-android-ui-components-sample/libs/MiPush_SDK_Client_5_0_6-G_3rd.aar
Labels: core, merge-before-release

#3892 Jump to newest message with refrsh
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/models/QueryChannelRequest.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/SearchLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/internal/ChatClientStateCalls.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImplTest.kt
Labels: merge-before-release

#3909 Moving user set in clientState
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/WhenConnectUser.kt
Labels: core

#3926 [3919] App crashes when reacting to a message in a thread
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/plugin/listeners/ThreadQueryListener.kt
  stream-chat-android-compose/detekt-baseline.xml
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/listener/internal/ThreadQueryListenerImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/thread/internal/ThreadLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/sync/internal/SyncManager.kt
Labels: bug, core

#3923 [3787] Move some classes from ui-common to ui-components module
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/build.gradle
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/enums/OnlineStatus.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/DateFormatter.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/DefaultDateFormatter.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/LegacyDateFormatter.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/Utils.java
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/roundedImageView/PorterImageView.java
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/roundedImageView/PorterShapeImageView.java
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/strings/ChatStrings.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/strings/ChatStringsImpl.kt
  stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/MockChatClientBuilder.kt
  stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/Mother.kt
  stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/utils/LegacyDateFormatterTest.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/build.gradle
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/adapter/MessageListItem.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/enums/GiphyAction.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/images/ViewExtensions.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/navigation/ChatNavigationHandler.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/navigation/ChatNavigator.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/navigation/destinations/ChatDestination.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/GridSpacingItemDecoration.java
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/Linkify.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/ListenerDelegate.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/PermissionChecker.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/StartStopBuffer.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/ConstraintLayout.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/EditTextExtensions.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/LiveData.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/MessageItem.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/View.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/utils/extensions/ViewGroup.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/view/EndlessMessageListScrollListener.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/view/EndlessScrollListener.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/view/messages/MessageListItemWrapper.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListItemLiveData.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/ReplyDecorator.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/MessageListItemLiveDataTest.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/Mother.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/utils/StartStopBufferTest.kt
Labels: compose, ui-components

#3880 [ISSUE-3795] Network state in client state
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/ClientState.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/setup/state/internal/ClientStateImpl.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/Mother.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/errorhandler/factory/internal/OfflineErrorHandlerFactories.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventBatchUpdate.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/internal/GlobalMutableState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/utils/internal/ChannelUtils.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/event/EventHandlerImplTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/event/TotalUnreadCountTest.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImplTest.kt
Labels: core

#3924 [3912] keyboard capitalisation customisation
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/InputField.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/composer/MessageInput.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/composer/MessageComposer.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerViewStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerCenterContent.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputViewStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/internal/MessageInputFieldView.kt
  stream-chat-android-ui-components/src/main/res/values/attrs_message_composer_view.xml
  stream-chat-android-ui-components/src/main/res/values/attrs_message_input_view.xml
Labels: compose, ui-components

#3943 [3942] Fix the display of disconnected state
  CHANGELOG.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Labels: core

#3820 [ISSUE-3712] Separate message preparation part for SendMessageInterceptor
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/build.gradle
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/interceptor/SendMessageInterceptor.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/interceptor/message/PrepareMessageLogic.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/interceptor/message/PrepareMessageLogicFactory.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/interceptor/message/internal/PrepareMessageLogicImpl.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/interceptor/message/internal/PrepareMessageLogicImplTest.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImpl.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/interceptor/internal/SendMessageInterceptorImplTest.kt
Labels: core

#3965 Update Compose to 1.2.0, Kotlin to 1.7.0, and target SDK to 32
  CHANGELOG.md
  buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
  buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/handlers/PermissionHandler.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/preview/ImagePreviewActivity.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/channels/header/ChannelListHeader.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/attachments/images/ImagesPicker.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messages/MessagesScrollingOption.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/reactionoptions/ExtendedReactionsOptions.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/reactionpicker/ReactionsPicker.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/userreactions/UserReactions.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/AttachmentsPicker.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/Channels.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/Events.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/cms/UnreadCounts.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/messages/ReactionsPicker.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/channel/internal/ChannelStateLogicImpl.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/input/MessageInputView.kt
Labels: compose

#3939 [3936] channel list filter change
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-state/api/stream-chat-android-state.api
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/logic/querychannels/internal/QueryChannelsLogic.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/querychannels/ChannelsStateData.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/querychannels/internal/QueryChannelsMutableState.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/ChannelListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/internal/SimpleChannelListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModelBinding.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/LiveData.kt
Labels: bug, ui-components, core

#3966 Update deprecations
  DEPRECATIONS.md
  stream-chat-android-state/api/stream-chat-android-state.api
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/utils/SelfUserUtils.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/GlobalState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/plugin/state/global/internal/GlobalMutableState.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/offline/reactions/DeleteReactionsTests.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/viewmodels/ChannelListViewModelTest.kt
Labels: merge-before-release

#3950 [3949] Improve options overlay customizability
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/options/message/internal/MessageOptionsDialogFragment.kt
  stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
Labels: ui-components, merge-before-release

#3968 [3967] Deprecate `DefaultTypingUpdatesBuffer`
  CHANGELOG.md
  DEPRECATIONS.md
  docusaurus/docs/Android/03-ui/04-message-components/04-message-input.mdx
  docusaurus/docs/Android/04-compose/05-message-components/04-message-composer.mdx
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/messages/MessageComposer.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/messages/MessageInput.kt
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/typing/DefaultTypingUpdatesBuffer.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/MessageInputViewModel.kt
Labels: merge-before-release

#3958 [3668] Fix file provider
  CHANGELOG.md
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/StreamFileProvider.java
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/StreamFileProvider.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/model/AttachmentMetaData.kt
  stream-chat-android-ui-common/src/main/res/xml/stream_filepaths.xml
Labels: compose, ui-components, merge-before-release

#3953 [3265] Remove user related options from messages screen
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/components/messageoptions/MessageOptions.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/state/MessageAction.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListViewStyle.kt
  stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
Labels: compose, ui-components, merge-before-release

#3960 Cancel children jobs when ChatClient is disconnected
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Labels: core, merge-before-release
