Repository GetStream/stream-chat-android, pull requests merged in 2022-02, with the labels that each got.

#2994 Fix marking read after sending a message
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
Labels: core

#3002 [2996] Improve suggestion popup in new message composer
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerSuggestionsPopup.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/MessageComposerViewModelBinding.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/content/DefaultMessageComposerMentionSuggestionsContent.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_suggestion_list_view.xml
Labels: ui-components

#3007 [2902] Eliminate `ChatDomain::deleteChannel`
  CHANGELOG.md
  DEPRECATIONS.md
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/channel/ChannelListViewModel.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomain.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/DeleteChannel.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/ChatInfoViewModel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
Labels: core

#3010 Sync cached channels after setting the user
  CHANGELOG.md
  buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/ChannelDao.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/ChannelRepository.kt
Labels: core

#2929 Add extension ChatClient::loadMessageById
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/RetrofitCallAdapterFactory.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/GetMessageListener.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/call/CallTests.kt
  stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/Call.kt
  stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/ReturnOnErrorCall.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/LoadMessageById.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/viewmodel/messages/MessageListViewModel.kt
Labels: core

#3008 [2901] Eliminate `ChatDomain::hideChannel`
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/Plugin.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/HideChannelListener.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/utils/PairExtensions.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
Labels: core

#3009 [2900] Eliminate `ChatDomain::markAllRead`
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/ChannelApi.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/MarkAllReadListener.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/MarkAllRead.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/usecase/MarkAllReadTest.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/viewmodel/ChannelListViewModel.kt
Labels: core

#2932 Giphy resize based on fixed height
  CHANGELOG.md
  docusaurus/docs/Android/03-ui/05-components/05-message-list.mdx
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/CoilStreamImageLoader.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/StreamImageLoader.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/images/ViewExtensions.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/Int.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/MessageListItemViewHolderFactory.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/MessageListItemViewType.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemViewTypeMapper.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/GiphyMediaAttachmentViewStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/MediaAttachmentViewStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/GiphyMediaAttachmentView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/MediaAttachmentView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/MediaAttachmentsGroupView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/attachment/AttachmentViewFactory.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/AvatarDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/BackgroundDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/BaseDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/FailedIndicatorDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/GapDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/MaxPossibleWidthDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/MessageContainerMarginDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/PinIndicatorDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/ReactionsDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/ReplyDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/TextDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/GiphyAttachmentViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/GiphyViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/TextAndAttachmentsViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/GiphyInfoType.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_giphy_media_attachment_view.xml
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_giphy_attachment.xml
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_giphy.xml
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_media_attachment_view.xml
  stream-chat-android-ui-components/src/main/res/values/attrs_giphy_media_attachment_view.xml
  stream-chat-android-ui-components/src/main/res/values/attrs_media_attachment_view.xml
  stream-chat-android-ui-components/src/main/res/values/styles.xml
Labels: enhancement, performance, feature request, ui-components

#3069 Move retry related logic to LLC
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/call/RetryCall.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/Call.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/extensions/ChatError.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/retry/CallRetryService.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/retry/NoRetryPolicy.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/retry/RetryPolicy.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/call/CallTests.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/extensions/ChatErrorTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/DevTokenTest.kt
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/Android.java
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomain.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/livedata/utils/RetryPolicy.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomain.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/CreateChannelService.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/configuration/Config.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/EditMessageListenerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/MessageSendingService.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/MessageSendingServiceFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/utils/DefaultRetryPolicy.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/utils/NoRetryPolicy.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/utils/RetryPolicy.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/ChatDomainImplCreateChannelTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/ChatDomainImplTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/ChannelControllerReactionsTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/WhenSendMessage.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/BaseDomainTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/BaseDomainTest2.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/message/messagesendingservice/WhenObserveAttachmentsDBFlow.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/message/messagesendingservice/WhenSendNewMessage.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/utils/NoRetryPolicy.kt
Labels: core

#3076 Migrate ChatDomain::deleteReaction
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/DeleteReactionListener.kt
  stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/Call.kt
  stream-chat-android-core/src/main/java/io/getstream/chat/android/client/call/ReturnOnErrorCall.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/DeleteReactionListenerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/EditMessageListenerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/reaction/ReactionDao.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/reaction/ReactionRepository.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/DeleteReaction.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/ChannelControllerReactionsTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/reactions/DeleteReactionsTests.kt
Labels: core

#3081 Added an attribute to customize the search input height
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchInputView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/SearchInputViewStyle.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_search_view.xml
  stream-chat-android-ui-components/src/main/res/values/attrs_search_input_view.xml
  stream-chat-android-ui-components/src/main/res/values/dimens.xml
  stream-chat-android-ui-components/src/main/res/values/styles.xml
Labels: customer-request, ui-components

#3082 Fix setting custom empty and loading views for MessageListView
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_list_view.xml
Labels: ui-components

#3084 Introduce error handler
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/ErrorHandler.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/factory/ErrorHandlerFactory.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/factory/NoOpErrorHandlerFactory.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/listeners/DeleteReactionErrorHandler.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/factory/PluginFactory.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/DeleteReactionListener.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/utils/DevTokenTest.kt
  stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/OfflineErrorHandler.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/factory/OfflineErrorHandlerFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/listener/DeleteReactionErrorHandlerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/DeleteReactionListenerImpl.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
Labels: core

#3085 [2883] Add possibility to customizae date formatters
  CHANGELOG.md
  docusaurus/docs/Android/03-ui/03-chatui.mdx
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/Android.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/DateFormatter.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentGalleryActivity.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mention/list/MentionListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/mention/list/internal/MentionListAdapter.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/preview/internal/MessagePreviewView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/pinned/list/PinnedMessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/pinned/list/internal/PinnedMessageListAdapter.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/internal/SearchResultListAdapter.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/search/list/SearchResultListView.kt
Labels: ui-components

#3070 [3023] create `LinkAttachmentsViewHolder`
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/MessageListItemViewHolderFactory.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/MessageListItemViewType.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/internal/MessageListItemViewTypeMapper.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/view/internal/ImageAttachmentsGroupView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/AvatarDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/BackgroundDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/BaseDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/FailedIndicatorDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/GapDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/MaxPossibleWidthDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/MessageContainerMarginDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/PinIndicatorDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/ReactionsDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/ReplyDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/decorator/internal/TextDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/LinkAttachmentsViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/background/MessageBackgroundFactory.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/background/MessageBackgroundFactoryImpl.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_link_attachment.xml
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_link_attachments_view.xml
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_reply_view.xml
Labels: ui-components

#3090 [3089] Fix default events handler
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/EventMapping.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/EventDtos.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/events/ChatEvent.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/ChatEventHandler.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandler.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/Mother.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/querychannels/DefaultChatEventHandlerTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/utils/TestDataHelper.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/channel/list/CustomEventHandler.kt
Labels: ui-components

#3092 [2880] Remove ExoPlayer dependency from Compose
  CHANGELOG.md
  stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ui/login/CustomLoginActivity.kt
  stream-chat-android-compose-sample/src/main/res/drawable/ic_back.xml
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/mediapreview/MediaPreviewActivity.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/header/MessageListHeader.kt
  stream-chat-android-compose/src/main/res/drawable/stream_compose_ic_arrow_back.xml
  stream-chat-android-ui-common/build.gradle
  stream-chat-android-ui-components/build.gradle
Labels: compose

#3098 [2880] Remove ExoPlayer from UI components
  CHANGELOG.md
  build.gradle
  buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/build.gradle
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/navigation/destinations/AttachmentDestination.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/gallery/AttachmentMediaActivity.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_activity_attachment_media.xml
Labels: ui-components

#3096 Migrate ChatDomain::sendReaction
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/channel/ChannelClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/listeners/DeleteReactionErrorHandler.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/errorhandler/listeners/SendReactionErrorHandler.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/SendReactionListener.kt
  stream-chat-android-compose-sample/src/main/java/io/getstream/chat/android/compose/sample/ChatHelper.kt
  stream-chat-android-offline/api/stream-chat-android-offline.api
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/factory/SendReactionErrorHandlerFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/listener/DeleteReactionErrorHandlerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/errorhandler/listener/SendReactionErrorHandlerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/DeleteReactionListenerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/SendReactionListenerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/Reaction.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/usecase/SendReaction.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/ChannelControllerReactionsTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/BaseDomainTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/integration/BaseDomainTest2.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/reactions/DeleteReactionsTests.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/reactions/SendReactionsTests.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
Labels: core

#3112 [3111] Fix channel unread count for muted channels
  CHANGELOG.md
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventBatchUpdate.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/message/Extensions.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/utils/ChannelUtils.kt
Labels: bug, core

#3121 Fix updating ChatDomain::totalUnreadCount and ChatDomain::channelUnreadCount
  CHANGELOG.md
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/event/EventHandlerImpl.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/ChatDomainImplReplayEventsForActiveChannelsTest.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/event/TotalUnreadCountTest.kt
Labels: core

#3127 Expose `channelConfig` inside `ChannelState`
  CHANGELOG.md
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/channel/ChannelController.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/logic/ChannelLogic.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/state/ChannelMutableState.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/channel/state/ChannelState.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/channel/controller/WhenKeystroke.kt
Labels: core

#3138 Fix updating the DB after sending the message
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/SendMessageListenerImpl.kt
Labels: core

#3126 Move sendGiphy method to LLC
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/SendGiphyListener.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/SendGiphyListenerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/SendReactionListenerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
Labels: core

#3141 Move shuffleGiphy method to LLC
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/experimental/plugin/listeners/ShuffleGiphyListener.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/ChatDomainImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/OfflinePlugin.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/factory/StreamOfflinePluginFactory.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/experimental/plugin/listener/ShuffleGiphyListenerImpl.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/extensions/ChatClient.kt
Labels: core

#3149 Fix displaying long usernames in footnote view
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_item_message_footnote.xml
Labels: ui-components
