Repository GetStream/stream-chat-android, pull requests merged in 2023-09, with the labels that each got.

#4942 [i118] Fix NPE in StreamWebSocket (onFailure)
  CHANGELOG.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/StreamWebSocket.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/experimental/ws/StreamWebSocketTest.kt
Labels: bug, v6

#4943 [i118] Fix NPE in StreamWebSocket (onFailure)
  CHANGELOG.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/experimental/ws/StreamWebSocket.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/experimental/ws/StreamWebSocketTest.kt
Labels: bug, v5

#4945 [i116] Extend PushMessage to access extra data
  CHANGELOG.md
  buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
  stream-chat-android-client/detekt-baseline.xml
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/ChatPushDelegate.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/parser/StreamPayloadParser.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/notifications/parser/StreamPayloadParserTest.kt
  stream-chat-android-core/api/stream-chat-android-core.api
  stream-chat-android-core/src/main/java/io/getstream/chat/android/models/PushMessage.kt
Labels: enhancement, v6

#4948 [i119] fix crash on playing async voice message
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/detekt-baseline.xml
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/AudioPlayer.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/NativeMediaPlayer.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/StreamAudioPlayer.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/audio/NativeMediaPlayerMock.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/audio/StreamMediaPlayerTest.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/attachments/content/AudioRecordAttachmentContent.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/AudioRecordingController.kt
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/attachment/preview/factory/AudioRecordAttachmentPreviewFactory.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/AudioRecordPlayerView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/AudioRecordingAttachmentsGroupView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/AudioWavesSeekBar.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/FileAttachmentsView.kt
Labels: bug, v6

#4955 [i129] provide non-fatal error handling mechanism
  CHANGELOG.md
  docusaurus/docs/Android/01-basics/07-debugging.mdx
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/debugger/ChatClientDebugger.kt
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/docusaurus/Debugging.java
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/Debugging.kt
  stream-chat-android-ui-components-sample/detekt-baseline.xml
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/debugger/CustomChatClientDebugger.kt
Labels: enhancement, v5

#4956 [i126] fix user avatar click on channel list view
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
Labels: bug, v5

#4957 [i126] fix user avatar click on channel list view
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/internal/ChannelViewHolder.kt
Labels: bug, v6

#4958 [i127] align with changes made for v5
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/StreamLifecycleObserver.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/network/NetworkStateProvider.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/internal/ChatClientStateCalls.kt
Labels: v6

#4950 [i121] support deleted_reply_count prop in Message
  CHANGELOG.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MessageMapping.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/MessageDtos.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/MessageDtoTestData.kt
  stream-chat-android-core/api/stream-chat-android-core.api
  stream-chat-android-core/src/main/java/io/getstream/chat/android/models/Message.kt
  stream-chat-android-core/src/testFixtures/kotlin/io/getstream/chat/android/Mother.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageEntity.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageMapper.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/ReplyMessageEntity.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/Mother.kt
Labels: enhancement, v6

#4960 [i121] support deleted_reply_count prop in Message
  CHANGELOG.md
  stream-chat-android-client-test/api/stream-chat-android-client-test.api
  stream-chat-android-client-test/src/main/java/io/getstream/chat/android/client/test/Mother.kt
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/MessageMapping.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/model/dto/MessageDtos.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/Message.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/EventChatJsonProvider.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser2/testdata/MessageDtoTestData.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageEntity.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageMapper.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/Mother.kt
  stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/Mother.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/Mother.kt
  stream-chat-android-ui-uitests/src/androidTest/resources/http_message.json
  stream-chat-android-ui-uitests/src/androidTest/resources/ws_message_new.json
Labels: enhancement, v5
