Repository GetStream/stream-chat-android, pull requests merged in 2023-12, with the labels that each got.

#5100 Remove unnecessary user updates
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/event/handler/internal/EventHandlerSequential.kt
Labels: v6

#5106 Fix Message.ownReactions incorrect
  CHANGELOG.md
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/channel/thread/internal/ThreadLogic.kt
Labels: bug, v6

#5105 [i222] allow connect user with user_id only
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api2/mapping/UserMapping.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/User.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketFactory.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/parser/EventArguments.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/socket/SocketFactoryTest.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/user/internal/DatabaseUserRepository.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventHandlerSequential.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/utils/SelfUserUtils.kt
Labels: enhancement, core, v5

#5108 Fix Regex not escaped in getOccurrenceRanges
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/extensions/internal/String.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/common/extensions/StringTest.kt
Labels: bug, v5

#5109 Fix Regex not escaped in getOccurrenceRanges
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/String.kt
  stream-chat-android-ui-components/src/test/kotlin/io/getstream/chat/android/ui/common/extensions/StringTest.kt
Labels: bug, v6

#5104 [i192] remove attachment picker limitation in compose
  CHANGELOG.md
  docusaurus/docs/Android/05-compose/05-message-components/05-attachments-picker.mdx
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/AttachmentsPicker.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/attachments/factory/AttachmentsPickerTabFactory.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/util/StorageHelperWrapper.kt
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/compose/messages/AttachmentsPicker.kt
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/detekt-baseline.xml
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/helper/internal/StorageHelper.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/state/messages/composer/AttachmentMetaData.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/composer/internal/AttachmentMetaDataMapper.kt
Labels: enhancement, compose, v6

#5120 [i227] fix crash in audio player after relogin
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/detekt-baseline.xml
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/NativeMediaPlayer.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/audio/StreamAudioPlayer.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/audio/NativeMediaPlayerMock.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/MessageReplyView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/AudioRecordingAttachmentsGroupView.kt
Labels: bug, ui-components, core, v6

#5123 [i228] Support auto-translation feature in XML
  CHANGELOG.md
  docusaurus/docs/Android/04-ui/06-guides/05-custom-translations.mdx
  docusaurus/docs/Android/05-compose/07-guides/05-custom-translations.mdx
  stream-chat-android-markdown-transformer/api/stream-chat-android-markdown-transformer.api
  stream-chat-android-markdown-transformer/src/main/kotlin/io/getstream/chat/android/markdown/MarkdownTextTransformer.kt
  stream-chat-android-ui-components-sample/src/demo/kotlin/io/getstream/chat/ui/sample/application/AppConfig.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/App.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/application/ChatInitializer.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/data/user/SampleUser.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/customlogin/CustomLoginViewModel.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/userlogin/UserLoginViewModel.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/ChatUI.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListItemStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/internal/MessageListItemDecoratorProvider.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/MessageReplyView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/view/internal/FootnoteView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/decorator/internal/FootnoteDecorator.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/internal/ErrorMessageViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/internal/SystemMessageViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/options/message/MessageOptionsDialogFragment.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/preview/internal/MessagePreviewView.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/helper/MessagePreviewFormatter.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Message.kt
  stream-chat-android-ui-components/src/main/res/values-en/strings_message_list.xml
  stream-chat-android-ui-components/src/main/res/values/attrs_message_list_view.xml
  stream-chat-android-ui-components/src/main/res/values/strings_message_list.xml
  stream-chat-android-ui-components/src/main/res/values/styles.xml
Labels: enhancement, ui-components, v6
