Repository GetStream/stream-chat-android, pull requests merged in 2023-11, with the labels that each got.

#5037 [i207] pass message with result in SendMessageDebugger
  CHANGELOG.md
  docusaurus/docs/Android/01-basics/07-debugging.mdx
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/debugger/SendMessageDebugger.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/debugger/ChatClientDebuggerTest.kt
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/client/docusaurus/Debugging.java
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/client/docusaurus/Debugging.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/debugger/CustomChatClientDebugger.kt
Labels: enhancement, core, v6

#5042 [V5] Use shortService instead of dataSync for our workmanager job
  CHANGELOG.md
  buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
  stream-chat-android-client/src/main/AndroidManifest.xml
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/LoadNotificationDataWorker.kt
Labels: v5

#5043 [i208] center channel title when no last message
  CHANGELOG.md
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/internal/ChannelViewHolder.kt
Labels: bug, ui-components, v6

#5045 [i209] allow override channel options visibility
  docusaurus/android_versioned_docs/version-5.x.x/03-ui/03-channel-components/02-channel-list.mdx
  docusaurus/android_versioned_docs/version-5.x.x/assets/xml_customizing_swipe_actions.png
  docusaurus/docs/Android/04-ui/03-channel-components/02-channel-list.mdx
  docusaurus/docs/Android/assets/xml_customizing_swipe_actions.png
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/ChannelListVisibilityContainerImpl.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/internal/ChannelViewHolder.kt
Labels: enhancement, ui-components, v6

#5050 [i211] Customize deleted message UI
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/MessageListItemStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/internal/MessageDeletedViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/background/MessageBackgroundFactoryImpl.kt
Labels: enhancement, ui-components, v6

#5051 [i211] Customize deleted message UI
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/MessageListItemStyle.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/adapter/viewholder/internal/MessageDeletedViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/list/background/MessageBackgroundFactoryImpl.kt
Labels: enhancement, ui-components, v5

#5059 [i214] Preserve default behaviour when binding composer VM
  CHANGELOG.md
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/message/composer/viewmodel/MessageComposerViewModelBinding.kt
Labels: enhancement, ui-components, v5

#5063 Remove old workflow triggers
  .github/workflows/app-distribute.yml
  .github/workflows/build-and-test.yml
Labels: v6

#5069 Fix Gzip compression (v5)
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/interceptor/HeadersInterceptor.kt
Labels: v5

#5072 [i208] fix channel title position when typing
  stream-chat-android-ui-components/detekt-baseline.xml
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/channel/list/adapter/viewholder/internal/ChannelViewHolder.kt
Labels: bug, ui-components, v5

#5074 Preload KClass members for our DTO classes
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
Labels: performance, v6

#5076 Asynchronously create ChannelMutableState()
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsStateLogic.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/logic/querychannels/internal/QueryChannelsStateLogicTest.kt
Labels: performance, v6

#5078 Delay reflection in NotificationHandlerFactory
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/notifications/handler/NotificationHandlerFactory.kt
Labels: performance, v6

#5070 Faster ISO date formatter / parser
  buildSrc/src/main/kotlin/io/getstream/chat/android/Dependencies.kt
  stream-chat-android-client/build.gradle
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/internal/StreamDateFormatter.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/helper/DateFormatter.kt
Labels: performance, v6

#5082 Cache dateformat used by UI
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/helper/DateFormatter.kt
Labels: performance

#5083 Replace stateIn with DerivedStateFlow in ChannelMutableState (perf im…
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/StateRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/utils/internal/DerivedStateFlow.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/state/channel/controller/WhenHandleEvent.kt
Labels: performance, v6

#5081 Faster SocketListener callback delivery
  CHANGELOG.md
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/ChatSocket.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/socket/SocketListener.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/utils/observable/ChatEventsObservable.kt
Labels: performance

#5079 Fix skip slow mode capability not handled
  CHANGELOG.md
  stream-chat-android-core/api/stream-chat-android-core.api
  stream-chat-android-core/src/main/java/io/getstream/chat/android/models/ChannelCapabilities.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt
Labels: v6

#5080 Fix skip slow mode capability not handled
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/models/ChannelCapabilities.kt
  stream-chat-android-ui-common/detekt-baseline.xml
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/common/composer/MessageComposerController.kt
Labels: v5

#5093 Use a Sealed Class for VersionPrefixHeader (V5)
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/header/VersionPrefixHeader.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/common/ChatUIInitializer.kt
Labels: v5
