Repository GetStream/stream-chat-android, pull requests merged in 2023-10, with the labels that each got.

#4981 add caching to date parser
  stream-chat-android-client/detekt-baseline.xml
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/DateAdapter.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/ExactDateAdapter.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/internal/StreamDateFormatter.kt
Labels: v6

#4978 add caching to date parser
  stream-chat-android-client/detekt-baseline.xml
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/DateAdapter.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/ExactDateAdapter.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/parser2/adapters/internal/StreamDateFormatter.kt
Labels: v5

#4980 Ignore push messages if WS is connected
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/debug/java/io/getstream/chat/android/client/di/ChatModule.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/ChatClient.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/api/ChatClientConfig.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/di/BaseChatModule.kt
  stream-chat-android-client/src/release/java/io/getstream/chat/android/client/di/ChatModule.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/ConnectUserTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/MockClientBuilder.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/api/ClientConnectionTests.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/chatclient/BaseChatClientTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/debugger/ChatClientDebuggerTest.kt
  stream-chat-android-client/src/test/java/io/getstream/chat/android/client/user/CurrentUserFetcherTests.kt
Labels: v5

#4976 Improve db cache
  stream-chat-android-client/api/stream-chat-android-client.api
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/UserRepository.kt
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/persistance/repository/noop/NoOpUserRepository.kt
  stream-chat-android-offline/detekt-baseline.xml
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/database/internal/ChatDatabase.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/ChannelEntityUtils.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/channel/internal/DatabaseChannelRepository.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/DatabaseMessageRepository.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/message/internal/MessageEntity.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/domain/user/internal/DatabaseUserRepository.kt
  stream-chat-android-offline/src/main/java/io/getstream/chat/android/offline/repository/factory/internal/DatabaseRepositoryFactory.kt
  stream-chat-android-offline/src/test/java/io/getstream/chat/android/offline/repository/domain/channel/internal/ChannelRepositoryImplTest.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/offline/event/handler/internal/EventBatchUpdate.kt
  stream-chat-android-ui-common/src/main/kotlin/com/getstream/sdk/chat/utils/DateFormatter.kt
  stream-chat-android-ui-common/src/test/kotlin/com/getstream/sdk/chat/utils/DefaultDateFormatterTest.kt
Labels: v5

#5014 [i200] add MessageDateSeparatorTheme
  CHANGELOG.md
  stream-chat-android-compose/api/stream-chat-android-compose.api
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/messages/list/MessageContainer.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/ChatTheme.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/MessageDateSeparatorTheme.kt
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/ui/theme/StreamColors.kt
  stream-chat-android-compose/src/main/res/values/colors.xml
Labels: enhancement, compose, v5

#5026 [i202] encode filename before uploading
  CHANGELOG.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
Labels: bug, core, v5

#5027 [i202] encode filename before uploading
  CHANGELOG.md
  stream-chat-android-client/src/main/java/io/getstream/chat/android/client/uploader/StreamFileUploader.kt
Labels: bug, core, v6
