Repository GetStream/stream-chat-android, pull requests merged in 2023-07, with the labels that each got.

#4868 Feature/channel typing indicator v6
  CHANGELOG.md
  stream-chat-android-docs/src/main/java/io/getstream/chat/docs/java/ui/channels/ChannelList.java
  stream-chat-android-docs/src/main/kotlin/io/getstream/chat/docs/kotlin/ui/channels/ChannelList.kt
  stream-chat-android-ui-components-sample/src/main/kotlin/io/getstream/chat/ui/sample/feature/chat/info/shared/ChatInfoSharedGroupsViewHolderFactory.kt
  stream-chat-android-ui-components/api/stream-chat-android-ui-components.api
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/ChannelListItem.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/ChannelListPayloadDiff.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/internal/ChannelListItemAdapter.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/internal/ChannelListItemDiffCallback.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/BaseChannelListItemViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/internal/ChannelListLoadingMoreViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/internal/ChannelViewHolder.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/utils/extensions/Channel.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/viewmodel/channels/ChannelListViewModelBinding.kt
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_channel_list_item_foreground_view.xml
  stream-chat-android-ui-uitests/src/androidTest/java/io/getstream/chat/android/uitests/snapshot/uicomponents/channels/ChannelListItemViewTest.kt
Labels: merge before v6 release

#4880 Create a `destroy()` method for our States
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/factory/StreamStatePluginFactory.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/logic/internal/LogicRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/StateRegistry.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/internal/ChannelMutableState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/channel/thread/internal/ThreadMutableState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/global/internal/MutableGlobalState.kt
  stream-chat-android-state/src/main/java/io/getstream/chat/android/state/plugin/state/querychannels/internal/QueryChannelsMutableState.kt
  stream-chat-android-state/src/test/java/io/getstream/chat/android/state/plugin/logic/channel/internal/ChannelStateLogicTest.kt
Labels: v6-candidate

#4884 [4761] add migration guide for AvatarView
  docusaurus/docs/Android/02-migration-guides/03-ui-components/04-avatar-view.mdx
Labels: v6-beta

#4886 [4885] migration guide for StreamLog
  docusaurus/docs/Android/02-migration-guides/01-client/04-logging.mdx
Labels: v6-beta

#4883 [i99] fix crash on notification click
  stream-chat-android-compose/src/main/java/io/getstream/chat/android/compose/viewmodel/messages/MessageListViewModel.kt
Labels: v5

#4898 [i74] fix multiline support in XML message composer
  stream-chat-android-ui-components/src/main/res/layout/stream_ui_message_composer_default_center_content.xml
Labels: v6-beta

#4899 [4042] fix issue of link attachment not being shown
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/messages/list/adapter/viewholder/attachment/UnsupportedAttachmentFactory.kt
Labels: v6-beta

#4904 Fix/typing indicator on channel list
  CHANGELOG.md
  stream-chat-android-ui-common/api/stream-chat-android-ui-common.api
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/feature/messages/composer/MessageComposerController.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/utils/typing/TypingUpdatesBuffer.kt
  stream-chat-android-ui-common/src/main/kotlin/io/getstream/chat/android/ui/common/utils/typing/internal/DefaultTypingUpdatesBuffer.kt
  stream-chat-android-ui-components/src/main/kotlin/io/getstream/chat/android/ui/feature/channels/list/adapter/viewholder/internal/ChannelViewHolder.kt
Labels: v6-beta
